### ISSUE TITLE
Support for PHP version 7

### ISSUE THREAD

**Issue by hendralin** [ardzz/wavel#2]
Hallo Mas,

Terima kasih sudah membuat package yang keren ini... ada yang mau saya tanyakan mengenai dukungan versi PHP apakah bisa untuk PHP versi 7?

Terima kasih

**Comment by ardzz** [comment]
Halo kak @hendralin , saat ini wavel tidak mendukung versi PHP 7. Dan package ini secara resmi belum dirilis.

Terimakasih

**Comment by ardzz** [comment]
Sebenernya bisa kok di downgrade ke PHP 7, tapi harus refactoring banyak kode kak. Soalnya fitur yang dipake dari PHP 8 itu hanya _type hinting,return type, dan mendefinisikan properti di parameter method \_\_constructor_ nya aja

**Comment by ardzz** [comment]
Nanti saya pertimbangkan lagi ya kak @hendralin, terimakasih atas issue nya. Semoga dapat segera rilis dan tersedia support PHP 7

**Comment by hendralin** [comment]
Terima kasih mas, skrng udah bisa dipakai di PHP 7
